#!/bin/bash  -e

docker run \
    -i \
    -t \
    --rm \
    -e DISPLAY=$DISPLAY \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -v /home/efarrer/.Xauthority:/root/.Xauthority \
    --net=host \
    google-chrome \
    /usr/bin/google-chrome --no-default-browser-check --user-data-dir=/root/.config/google-chrome/Default
